### ISSUE TITLE
Connections between same station can be added

### ISSUE THREAD

**Issue by tylrbvn** [SEPRFVS/FVS4#14]
The connection modifier currently allows a player to add a connection between a station and the same station, a check needs to be added to disallow this

![screen shot 2015-04-24 at 13 44 36](https://cloud.githubusercontent.com/assets/9434923/7318860/1a9d1052-ea88-11e4-89c6-abc2e54ed743.png)

**Comment by ghost** [comment]
Closed in 1eac8c3
