### ISSUE TITLE
Beautify the game

### ISSUE THREAD

**Issue by EllisF** [SEPRFVS/FVS4#7]

**Comment by alwaysbusy** [comment]
Top down trains
New UI style
Main Menu Screen
New Fonts

**Comment by alwaysbusy** [comment]
Font changed in fbd5c37
Sidebar 7bd6cc8 and d1277e8
Resouces, contorl buttons and tooltips have new style in 95d30b6, c910b47 and e8d7a7f

**Comment by alwaysbusy** [comment]
Trains in 46d8c3b
